"""add immutable cold delivery persistence

Revision ID: d3e4f5a6b7c8
Revises: c2d3e4f5a6b7
"""

from alembic import op
import sqlalchemy as sa


revision = "d3e4f5a6b7c8"
down_revision = "c2d3e4f5a6b7"
branch_labels = None
depends_on = None

_IMMUTABLE = (
    "cold_delivery_operations", "cold_message_contents", "cold_delivery_events", "cold_t3_decisions",
    "cold_provider_dispatches", "cold_provider_dispatch_references", "cold_provider_feedback_receipts",
)


def upgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        op.create_unique_constraint("uq_cold_authorizations_id_lead_contact", "cold_prospecting_authorizations", ["id", "lead_id", "contact_point_id"])
    op.create_table("cold_delivery_operations",
        sa.Column("id", sa.String(36), nullable=False), sa.Column("cold_authorization_id", sa.String(36), nullable=False), sa.Column("lead_id", sa.String(36), nullable=False), sa.Column("contact_point_id", sa.String(36), nullable=False), sa.Column("action", sa.String(32), nullable=False), sa.Column("purpose_key", sa.String(128), nullable=False), sa.Column("purpose_family", sa.String(128), nullable=False), sa.Column("source_namespace", sa.String(100), nullable=False), sa.Column("source_event_key", sa.String(512), nullable=False), sa.Column("message_content_fingerprint", sa.String(64), nullable=False), sa.Column("operation_schema_version", sa.String(128), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("action IN ('INITIAL','FOLLOW_UP')", name="ck_cold_delivery_operations_action"), sa.CheckConstraint("purpose_key LIKE 'cold_b2b:%'", name="ck_cold_delivery_operations_purpose"), sa.CheckConstraint("length(message_content_fingerprint)=64", name="ck_cold_delivery_operations_message_fingerprint"),
        sa.ForeignKeyConstraint(["cold_authorization_id", "lead_id", "contact_point_id"], ["cold_prospecting_authorizations.id", "cold_prospecting_authorizations.lead_id", "cold_prospecting_authorizations.contact_point_id"], name="fk_cold_delivery_operations_authorization_owner"), sa.ForeignKeyConstraint(["lead_id"], ["crm_leads.id"]), sa.ForeignKeyConstraint(["contact_point_id"], ["crm_contact_points.id"]), sa.PrimaryKeyConstraint("id"), sa.UniqueConstraint("cold_authorization_id", name="uq_cold_delivery_operations_authorization"), sa.UniqueConstraint("source_namespace", "source_event_key", name="uq_cold_delivery_operations_source"), sa.UniqueConstraint("id", "message_content_fingerprint", name="uq_cold_delivery_operations_message"))
    op.create_table("cold_message_contents",
        sa.Column("id", sa.String(36), nullable=False), sa.Column("operation_id", sa.String(36), nullable=False), sa.Column("content_fingerprint", sa.String(64), nullable=False), sa.Column("subject", sa.String(998), nullable=True), sa.Column("body", sa.Text(), nullable=False), sa.Column("content_format", sa.String(32), nullable=False), sa.Column("content_schema_version", sa.String(128), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("length(content_fingerprint)=64", name="ck_cold_message_contents_fingerprint"), sa.CheckConstraint("length(trim(body)) > 0", name="ck_cold_message_contents_body"), sa.CheckConstraint("lower(coalesce(subject, '')) NOT LIKE '%@%' AND lower(body) NOT LIKE '%@%' AND lower(coalesce(subject, '')) NOT LIKE '%{{%' AND lower(body) NOT LIKE '%{{%' AND lower(coalesce(subject, '')) NOT LIKE '%${%' AND lower(body) NOT LIKE '%${%' AND lower(coalesce(subject, '')) NOT LIKE '%recipient%' AND lower(body) NOT LIKE '%recipient%' AND lower(coalesce(subject, '')) NOT LIKE '%destination%' AND lower(body) NOT LIKE '%destination%' AND lower(coalesce(subject, '')) NOT LIKE '%api_key%' AND lower(body) NOT LIKE '%api_key%' AND lower(coalesce(subject, '')) NOT LIKE '%provider_secret%' AND lower(body) NOT LIKE '%provider_secret%' AND lower(coalesce(subject, '')) NOT LIKE '%bearer%' AND lower(body) NOT LIKE '%bearer%' AND lower(coalesce(subject, '')) NOT LIKE '%password%' AND lower(body) NOT LIKE '%password%' AND lower(coalesce(subject, '')) NOT LIKE '%secret%' AND lower(body) NOT LIKE '%secret%'", name="ck_cold_message_contents_no_routing_or_secrets"), sa.ForeignKeyConstraint(["operation_id", "content_fingerprint"], ["cold_delivery_operations.id", "cold_delivery_operations.message_content_fingerprint"]), sa.PrimaryKeyConstraint("id"), sa.UniqueConstraint("operation_id", name="uq_cold_message_contents_operation"))
    op.create_table("cold_delivery_operation_state",
        sa.Column("operation_id", sa.String(36), nullable=False), sa.Column("current_state", sa.String(32), nullable=False), sa.Column("revision", sa.Integer(), nullable=False), sa.Column("next_event_sequence", sa.Integer(), nullable=False), sa.Column("active_execution_id", sa.String(64), nullable=True), sa.Column("active_fence_identity", sa.String(255), nullable=True), sa.Column("next_technical_retry_at", sa.DateTime(timezone=True), nullable=True), sa.Column("reconciliation_status", sa.String(64), nullable=True), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("current_state IN ('CREATED','READY','T3_BLOCKED','DISPATCH_PLANNED','DISPATCHING','ACCEPTED','REJECTED','TECHNICAL_RETRY_DUE','RECONCILIATION_REQUIRED','UNRESOLVED_TERMINAL')", name="ck_cold_delivery_operation_state_value"), sa.CheckConstraint("revision >= 1", name="ck_cold_delivery_operation_state_revision"), sa.CheckConstraint("next_event_sequence >= 1", name="ck_cold_delivery_operation_state_sequence"), sa.ForeignKeyConstraint(["operation_id"], ["cold_delivery_operations.id"]), sa.PrimaryKeyConstraint("operation_id"))
    op.create_table("cold_delivery_events",
        sa.Column("id", sa.String(36), nullable=False), sa.Column("operation_id", sa.String(36), nullable=False), sa.Column("sequence_number", sa.Integer(), nullable=False), sa.Column("event_type", sa.String(64), nullable=False), sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False), sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False), sa.Column("source_namespace", sa.String(100), nullable=False), sa.Column("source_event_key", sa.String(512), nullable=False), sa.Column("event_fingerprint", sa.String(64), nullable=False), sa.Column("safe_payload", sa.JSON(), nullable=False),
        sa.CheckConstraint("sequence_number >= 1", name="ck_cold_delivery_events_sequence"), sa.CheckConstraint("length(event_fingerprint)=64", name="ck_cold_delivery_events_fingerprint"), sa.ForeignKeyConstraint(["operation_id"], ["cold_delivery_operations.id"]), sa.PrimaryKeyConstraint("id"), sa.UniqueConstraint("operation_id", "sequence_number", name="uq_cold_delivery_events_operation_sequence"), sa.UniqueConstraint("source_namespace", "source_event_key", name="uq_cold_delivery_events_source"))
    op.create_table("cold_t3_decisions",
        sa.Column("id", sa.String(36), nullable=False), sa.Column("operation_id", sa.String(36), nullable=False), sa.Column("cold_authorization_id", sa.String(36), nullable=False), sa.Column("authorization_fingerprint", sa.String(64), nullable=False), sa.Column("evaluated_at", sa.DateTime(timezone=True), nullable=False), sa.Column("policy_fingerprint", sa.String(64), nullable=False), sa.Column("authority_fingerprint", sa.String(64), nullable=False), sa.Column("crm_evidence_ids", sa.JSON(), nullable=False), sa.Column("recipient_fingerprint", sa.String(64), nullable=False), sa.Column("decision", sa.String(16), nullable=False), sa.Column("reason_codes", sa.JSON(), nullable=False), sa.Column("decision_schema_version", sa.String(128), nullable=False), sa.Column("source_namespace", sa.String(100), nullable=False), sa.Column("source_event_key", sa.String(512), nullable=False), sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("decision IN ('ALLOWED','BLOCKED')", name="ck_cold_t3_decisions_value"), sa.CheckConstraint("length(authorization_fingerprint)=64", name="ck_cold_t3_decisions_authorization_fingerprint"), sa.CheckConstraint("length(policy_fingerprint)=64", name="ck_cold_t3_decisions_policy_fingerprint"), sa.CheckConstraint("length(authority_fingerprint)=64", name="ck_cold_t3_decisions_authority_fingerprint"), sa.CheckConstraint("length(recipient_fingerprint)=64", name="ck_cold_t3_decisions_recipient_fingerprint"), sa.ForeignKeyConstraint(["operation_id"], ["cold_delivery_operations.id"]), sa.ForeignKeyConstraint(["cold_authorization_id"], ["cold_prospecting_authorizations.id"]), sa.PrimaryKeyConstraint("id"), sa.UniqueConstraint("source_namespace", "source_event_key", name="uq_cold_t3_decisions_source"))
    op.create_table("cold_provider_dispatches",
        sa.Column("id", sa.String(36), nullable=False), sa.Column("operation_id", sa.String(36), nullable=False), sa.Column("provider_key", sa.String(64), nullable=False), sa.Column("provider_contract_version", sa.String(128), nullable=False), sa.Column("provider_operation_key", sa.String(255), nullable=False), sa.Column("payload_fingerprint", sa.String(64), nullable=False), sa.Column("sender_fingerprint", sa.String(64), nullable=False), sa.Column("recipient_fingerprint", sa.String(64), nullable=False), sa.Column("dispatch_status", sa.String(32), nullable=False), sa.Column("planned_at", sa.DateTime(timezone=True), nullable=False), sa.Column("dispatch_started_at", sa.DateTime(timezone=True), nullable=True), sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("dispatch_status IN ('PLANNED','DISPATCHING','ACCEPTED','REJECTED','TECHNICAL_FAILURE')", name="ck_cold_provider_dispatches_status"), sa.CheckConstraint("length(payload_fingerprint)=64", name="ck_cold_provider_dispatches_payload_fingerprint"), sa.CheckConstraint("length(sender_fingerprint)=64", name="ck_cold_provider_dispatches_sender_fingerprint"), sa.CheckConstraint("length(recipient_fingerprint)=64", name="ck_cold_provider_dispatches_recipient_fingerprint"), sa.ForeignKeyConstraint(["operation_id"], ["cold_delivery_operations.id"]), sa.PrimaryKeyConstraint("id"), sa.UniqueConstraint("provider_key", "provider_operation_key", name="uq_cold_provider_dispatches_operation"))
    op.create_table("cold_provider_dispatch_references",
        sa.Column("id", sa.String(36), nullable=False), sa.Column("provider_dispatch_id", sa.String(36), nullable=False), sa.Column("provider_key", sa.String(64), nullable=False), sa.Column("provider_reference", sa.String(255), nullable=False), sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False), sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False), sa.ForeignKeyConstraint(["provider_dispatch_id"], ["cold_provider_dispatches.id"]), sa.PrimaryKeyConstraint("id"), sa.UniqueConstraint("provider_dispatch_id", name="uq_cold_provider_dispatch_references_dispatch"), sa.UniqueConstraint("provider_key", "provider_reference", name="uq_cold_provider_dispatch_references_value"))
    op.create_table("cold_provider_feedback_receipts",
        sa.Column("id", sa.String(36), nullable=False), sa.Column("provider_dispatch_id", sa.String(36), nullable=False), sa.Column("provider_key", sa.String(64), nullable=False), sa.Column("provider_event_key", sa.String(255), nullable=False), sa.Column("event_fingerprint", sa.String(64), nullable=False), sa.Column("received_at", sa.DateTime(timezone=True), nullable=False), sa.Column("interpretation_version", sa.String(128), nullable=False), sa.Column("interpretation_metadata", sa.JSON(), nullable=False), sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False), sa.CheckConstraint("length(event_fingerprint)=64", name="ck_cold_provider_feedback_receipts_fingerprint"), sa.ForeignKeyConstraint(["provider_dispatch_id"], ["cold_provider_dispatches.id"]), sa.PrimaryKeyConstraint("id"), sa.UniqueConstraint("provider_key", "provider_event_key", name="uq_cold_provider_feedback_receipts_event"))
    if op.get_bind().dialect.name == "postgresql":
        op.execute("CREATE FUNCTION prevent_cold_delivery_immutable_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'cold delivery immutable records are append-only'; END; $$")
        for table in _IMMUTABLE: op.execute(f"CREATE TRIGGER trg_{table}_append_only BEFORE UPDATE OR DELETE ON {table} FOR EACH ROW EXECUTE FUNCTION prevent_cold_delivery_immutable_mutation()")
        op.execute("""CREATE FUNCTION enforce_cold_delivery_state_transition() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.current_state <> OLD.current_state AND NOT ((OLD.current_state='CREATED' AND NEW.current_state IN ('READY','T3_BLOCKED','UNRESOLVED_TERMINAL')) OR (OLD.current_state='READY' AND NEW.current_state IN ('DISPATCH_PLANNED','T3_BLOCKED','RECONCILIATION_REQUIRED','UNRESOLVED_TERMINAL')) OR (OLD.current_state='DISPATCH_PLANNED' AND NEW.current_state IN ('DISPATCHING','TECHNICAL_RETRY_DUE','RECONCILIATION_REQUIRED','UNRESOLVED_TERMINAL')) OR (OLD.current_state='DISPATCHING' AND NEW.current_state IN ('ACCEPTED','REJECTED','TECHNICAL_RETRY_DUE','RECONCILIATION_REQUIRED','UNRESOLVED_TERMINAL')) OR (OLD.current_state='TECHNICAL_RETRY_DUE' AND NEW.current_state IN ('DISPATCH_PLANNED','RECONCILIATION_REQUIRED','UNRESOLVED_TERMINAL')) OR (OLD.current_state='RECONCILIATION_REQUIRED' AND NEW.current_state IN ('ACCEPTED','REJECTED','TECHNICAL_RETRY_DUE','UNRESOLVED_TERMINAL'))) THEN RAISE EXCEPTION 'invalid cold delivery state transition'; END IF; RETURN NEW; END; $$""")
        op.execute("CREATE TRIGGER trg_cold_delivery_operation_state_transition BEFORE UPDATE ON cold_delivery_operation_state FOR EACH ROW EXECUTE FUNCTION enforce_cold_delivery_state_transition()")


def downgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP TRIGGER IF EXISTS trg_cold_delivery_operation_state_transition ON cold_delivery_operation_state")
        op.execute("DROP FUNCTION IF EXISTS enforce_cold_delivery_state_transition()")
        for table in reversed(_IMMUTABLE): op.execute(f"DROP TRIGGER IF EXISTS trg_{table}_append_only ON {table}")
        op.execute("DROP FUNCTION IF EXISTS prevent_cold_delivery_immutable_mutation()")
    for table in ("cold_provider_feedback_receipts", "cold_provider_dispatch_references", "cold_provider_dispatches", "cold_t3_decisions", "cold_delivery_events", "cold_delivery_operation_state", "cold_message_contents", "cold_delivery_operations"): op.drop_table(table)
    if op.get_bind().dialect.name == "postgresql":
        op.execute("ALTER TABLE cold_prospecting_authorizations DROP CONSTRAINT IF EXISTS uq_cold_authorizations_id_lead_contact")
