"""add affiliate financial adjustments"""
from alembic import op
import sqlalchemy as sa
from app.database.types import UTCDateTime
revision="e7f8a9b0c1d2"; down_revision="d6e7f8a9b0c1"; branch_labels=None; depends_on=None
def upgrade():
 op.create_table("affiliate_financial_adjustments",sa.Column("id",sa.String(36),primary_key=True),sa.Column("affiliate_earning_id",sa.Integer,sa.ForeignKey("affiliate_earnings.id"),nullable=False),sa.Column("affiliate_program_id",sa.Integer,sa.ForeignKey("affiliate_programs.id"),nullable=False),sa.Column("affiliate_conversion_id",sa.Integer,sa.ForeignKey("affiliate_conversions.id")),sa.Column("affiliate_payout_id",sa.Integer,sa.ForeignKey("affiliate_payouts.id")),sa.Column("attribution_payout_settlement_link_id",sa.String(36),sa.ForeignKey("attribution_payout_settlement_links.id")),sa.Column("adjustment_type",sa.String(32),nullable=False),sa.Column("adjustment_amount",sa.Numeric(18,2),nullable=False),sa.Column("currency",sa.String(3),nullable=False),sa.Column("effective_at",UTCDateTime(),nullable=False),sa.Column("source_namespace",sa.String(63),nullable=False),sa.Column("source_event_digest",sa.String(64),nullable=False),sa.Column("fingerprint",sa.String(64),nullable=False),sa.Column("recorded_at",UTCDateTime(),nullable=False),sa.CheckConstraint("adjustment_type IN ('REFUND','REVERSAL','CHARGEBACK','CLAWBACK','CANCELLATION','CORRECTION','RESTORATION')",name="ck_affiliate_financial_adjustments_type"),sa.CheckConstraint("(adjustment_type IN ('REFUND','REVERSAL','CHARGEBACK','CLAWBACK','CANCELLATION') AND adjustment_amount < 0) OR (adjustment_type IN ('CORRECTION','RESTORATION') AND adjustment_amount > 0)",name="ck_affiliate_financial_adjustments_type_sign"),sa.CheckConstraint("source_namespace ~ '^[a-z][a-z0-9.-]{0,62}$'",name="ck_affiliate_financial_adjustments_namespace"),sa.CheckConstraint("source_event_digest ~ '^[0-9a-f]{64}$'",name="ck_affiliate_financial_adjustments_digest"),sa.CheckConstraint("fingerprint ~ '^[0-9a-f]{64}$'",name="ck_affiliate_financial_adjustments_fingerprint"),sa.UniqueConstraint("affiliate_program_id","source_namespace","source_event_digest",name="uq_affiliate_financial_adjustments_source"))
 op.execute("CREATE FUNCTION m10a7_reject_adjustment_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'financial adjustments are append-only'; END; $$")
 op.execute("CREATE TRIGGER trg_m10a7_adjustment_immutable BEFORE UPDATE OR DELETE ON affiliate_financial_adjustments FOR EACH ROW EXECUTE FUNCTION m10a7_reject_adjustment_mutation()")
def downgrade():
 op.execute("DROP TRIGGER IF EXISTS trg_m10a7_adjustment_immutable ON affiliate_financial_adjustments");op.execute("DROP FUNCTION IF EXISTS m10a7_reject_adjustment_mutation()");op.drop_table("affiliate_financial_adjustments")
