"""
Registry updater utilities.

Responsible for automatically updating
registry files generated by ETM CLI.
"""

from pathlib import Path

from core.logger import success, info


def append_if_missing(
    file_path: Path,
    text: str,
):

    if not file_path.exists():

        info(f"Registry not found: {file_path}")

        return

    content = file_path.read_text(
        encoding="utf-8"
    )

    if text in content:

        info(
            f"Already registered: {file_path.name}"
        )

        return

    with file_path.open(
        "a",
        encoding="utf-8",
    ) as f:

        f.write("\n")
        f.write(text)

    success(
        f"Updated {file_path.name}"
    )